### ISSUE TITLE
DR16 Fail State Timeout On Empty Packet

### ISSUE THREAD

**Issue by Pandabear1125** [CU-Robotics/firmware#13]
Need to implement fail state setting when there is a lack of packets. This needs to be done once the main timing system is set.

**Comment by LachlanMurphy** [comment]
This has been fixed in the "Add Safety Code" pull request. Timeout is 250 ms.

**Comment by LachlanMurphy** [comment]
This has been fixed in the "Add Safety Code" pull request. Timeout is 250 ms.
